#pragma once

#include <string>
#include <vector>
#include <memory>
#include <cstdint>
#include <array>
#include <glm/glm.hpp>
#include <glm/gtc/quaternion.hpp>

namespace veex {

// Forward declarations
class GameInfo;

// ============================================================================
// Source Engine MDL File Format Structures
// Based on Valve Source SDK 2013 studio.h
// ============================================================================

// Magic number: "IDST" in little-endian
constexpr int32_t MDL_IDST = (('T' << 24) | ('S' << 16) | ('D' << 8) | ('I' << 0)); // 0x54534449

// Supported MDL versions
constexpr int32_t MDL_VERSION_44 = 44; // Source 2004
constexpr int32_t MDL_VERSION_45 = 45; // Source 2006
constexpr int32_t MDL_VERSION_46 = 46; // Source 2007
constexpr int32_t MDL_VERSION_47 = 47; // Source 2009
constexpr int32_t MDL_VERSION_48 = 48; // Source 2011
constexpr int32_t MDL_VERSION_49 = 49; // Source 2013 (SDK2013)

// VVD (Vertex Data) magic
constexpr int32_t VVD_IDSV = (('V' << 24) | ('S' << 16) | ('D' << 8) | ('I' << 0)); // 0x56534449
constexpr int32_t VVD_VERSION = 4;

// VTX version for Source 2013
constexpr int32_t VTX_VERSION_7 = 7;

// ============================================================================
// Model Flags (from studio.h)
// ============================================================================
enum MDLFlags : uint32_t {
    STUDIOHDR_FLAGS_AUTOGENERATED_HITBOX          = 0x00000001,
    STUDIOHDR_FLAGS_USES_ENV_CUBEMAP              = 0x00000002,
    STUDIOHDR_FLAGS_FORCE_OPAQUE                  = 0x00000004,
    STUDIOHDR_FLAGS_TRANSLUCENT_TWOPASS           = 0x00000008,
    STUDIOHDR_FLAGS_STATIC_PROP                   = 0x00000010,
    STUDIOHDR_FLAGS_USES_FB_TEXTURE               = 0x00000020,
    STUDIOHDR_FLAGS_HASSHADOWLOD                  = 0x00000040,
    STUDIOHDR_FLAGS_USES_BUMPMAPPING              = 0x00000080,
    STUDIOHDR_FLAGS_USE_SHADOWLOD_MATERIALS       = 0x00000100,
    STUDIOHDR_FLAGS_OBSOLETE                      = 0x00000200,
    STUDIOHDR_FLAGS_UNUSED                        = 0x00000400,
    STUDIOHDR_FLAGS_NO_FORCED_FADE                = 0x00000800,
    STUDIOHDR_FLAGS_FORCE_PHONEME_CROSSFADE       = 0x00001000,
    STUDIOHDR_FLAGS_CONSTANT_DIRECTIONAL_LIGHT_DOT = 0x00002000,
    STUDIOHDR_FLAGS_FLEXES_CONVERTED              = 0x00004000,
    STUDIOHDR_FLAGS_BUILT_IN_PREVIEW_MODE         = 0x00008000,
    STUDIOHDR_FLAGS_AMBIENT_BOOST                 = 0x00010000,
    STUDIOHDR_FLAGS_DO_NOT_CAST_SHADOWS           = 0x00020000,
    STUDIOHDR_FLAGS_CAST_TEXTURE_SHADOWS          = 0x00040000,
    STUDIOHDR_FLAGS_SUBDIVISION_SURFACE           = 0x00080000,
    STUDIOHDR_FLAGS_NO_ANIM_EVENTS                = 0x00100000,
    STUDIOHDR_FLAGS_VERT_ANIM_FIXED_POINT_SCALE   = 0x00200000,
};

// ============================================================================
// Main Header (studiohdr_t) - 408 bytes total
// ============================================================================
#pragma pack(push, 1)
struct studiohdr_t {
    int32_t id;                 // Model format ID: "IDST" (0x49 0x44 0x53 0x54)
    int32_t version;            // Format version number
    int32_t checksum;           // Must match PHY and VTX files
    char name[64];              // Internal name of the model, null-padded
    int32_t dataLength;         // Data size of MDL file in bytes

    // Vectors (12 bytes each: 3 floats)
    glm::vec3 eyeposition;      // Position of player viewpoint relative to model origin
    glm::vec3 illumposition;    // Position for ambient light and cubemap reflections
    glm::vec3 hull_min;         // Corner of model hull box with least X/Y/Z values
    glm::vec3 hull_max;         // Opposite corner of model hull box
    glm::vec3 view_bbmin;       // Bounding box min for view culling
    glm::vec3 view_bbmax;       // Bounding box max for view culling

    uint32_t flags;             // Model flags (see MDLFlags)

    // Bone data (mstudiobone_t)
    int32_t bone_count;
    int32_t bone_offset;

    // Bone controller data (mstudiobonecontroller_t)
    int32_t bonecontroller_count;
    int32_t bonecontroller_offset;

    // Hitbox sets (mstudiohitboxset_t)
    int32_t hitbox_count;
    int32_t hitbox_offset;

    // Local animation descriptions (mstudioanimdesc_t)
    int32_t localanim_count;
    int32_t localanim_offset;

    // Local sequence descriptions (mstudioseqdesc_t)
    int32_t localseq_count;
    int32_t localseq_offset;

    int32_t activitylistversion;
    int32_t eventsindexed;

    // Texture data (mstudiotexture_t)
    int32_t texture_count;
    int32_t texture_offset;

    // Texture directory paths (series of null-terminated strings)
    int32_t texturedir_count;
    int32_t texturedir_offset;

    // Skin replacement tables
    int32_t skinreference_count;
    int32_t skinfamily_count;
    int32_t skinreference_index;

    // Body parts (mstudiobodyparts_t)
    int32_t bodypart_count;
    int32_t bodypart_offset;

    // Attachment points (mstudioattachment_t)
    int32_t attachment_count;
    int32_t attachment_offset;

    // Local nodes (single bytes + null-terminated strings)
    int32_t localnode_count;
    int32_t localnode_index;
    int32_t localnode_name_index;

    // Flex descriptors (mstudioflexdesc_t)
    int32_t flexdesc_count;
    int32_t flexdesc_index;

    // Flex controllers (mstudioflexcontroller_t)
    int32_t flexcontroller_count;
    int32_t flexcontroller_index;

    // Flex rules (mstudioflexrule_t)
    int32_t flexrules_count;
    int32_t flexrules_index;

    // IK chains (mstudioikchain_t)
    int32_t ikchain_count;
    int32_t ikchain_index;

    // Mouths (mstudiomouth_t)
    int32_t mouths_count;
    int32_t mouths_index;

    // Local pose parameters (mstudioposeparamdesc_t)
    int32_t localposeparam_count;
    int32_t localposeparam_index;

    // Surface property name (single null-terminated string)
    int32_t surfaceprop_index;

    // Key-value data (series of strings)
    int32_t keyvalue_index;
    int32_t keyvalue_count;

    // IK locks (mstudioiklock_t)
    int32_t iklock_count;
    int32_t iklock_index;

    float mass;                 // Mass in kilograms
    int32_t contents;           // Contents flag

    // Include models (mstudiomodelgroup_t)
    int32_t includemodel_count;
    int32_t includemodel_index;

    int32_t virtualModel;       // Placeholder for mutable void*

    // Animation blocks (mstudioanimblock_t)
    int32_t animblocks_name_index;
    int32_t animblocks_count;
    int32_t animblocks_index;

    int32_t animblockModel;     // Placeholder for mutable void*

    // Bone table name
    int32_t bonetablename_index;

    int32_t vertex_base;        // Placeholder for void*
    int32_t offset_base;        // Placeholder for void*

    uint8_t directionaldotproduct;
    uint8_t rootLod;
    uint8_t numAllowedRootLods;
    uint8_t unused0;
    int32_t unused1;

    // Flex controller UI (mstudioflexcontrollerui_t)
    int32_t flexcontrollerui_count;
    int32_t flexcontrollerui_index;

    float vertAnimFixedPointScale;
    int32_t unused2;

    // Offset to secondary header (studiohdr2_t)
    int32_t studiohdr2index;

    int32_t unused3;

    // Header is 408 bytes long as of SDK2013
};
static_assert(sizeof(studiohdr_t) == 408, "studiohdr_t must be 408 bytes");

// ============================================================================
// Secondary Header (studiohdr2_t)
// ============================================================================
struct studiohdr2_t {
    int32_t srcbonetransform_count;
    int32_t srcbonetransform_index;

    int32_t illumpositionattachmentindex;

    float flMaxEyeDeflection;   // If 0, equivalent to cos(30)

    // Linear bone data (mstudiolinearbone_t)
    int32_t linearbone_index;

    int32_t unknown[64];
};

// ============================================================================
// Texture Structure (mstudiotexture_t) - 64 bytes
// ============================================================================
struct mstudiotexture_t {
    int32_t name_offset;        // Offset for null-terminated string (relative to this struct)
    uint32_t flags;
    int32_t used;               // Padding/runtime
    int32_t unused;             // Padding
    int32_t material;           // Placeholder for IMaterial
    int32_t client_material;    // Placeholder for void*
    int32_t unused2[10];        // Final padding
    // Struct is 64 bytes long
};
static_assert(sizeof(mstudiotexture_t) == 64, "mstudiotexture_t must be 64 bytes");

// ============================================================================
// Bone Structure (mstudiobone_t)
// ============================================================================
struct mstudiobone_t {
    int32_t sznameindex;        // Offset to bone name
    int32_t parent;             // Parent bone index, -1 if root
    int32_t bonecontroller[6];  // Bone controller indices

    glm::vec3 pos;              // Default position
    glm::quat quat;             // Default quaternion
    glm::vec3 rot;              // Default rotation (Radian Euler)

    glm::vec3 posscale;         // Position scale
    glm::vec3 rotscale;         // Rotation scale

    glm::mat4x3 poseToBone;     // 3x4 matrix: transforms default bone pose to local space

    uint32_t qAlignment;        // 
    int32_t flags;              // Bone flags
    int32_t proctype;           // Procedural type
    int32_t procindex;          // Procedural rule index
    int32_t physicsbone;        // Physics bone index

    int32_t surfacepropidx;     // Surface property index
    int32_t contents;           // Contents flag

    int32_t unused[8];          // Unused
};

// ============================================================================
// Body Part Structure (mstudiobodyparts_t)
// ============================================================================
struct mstudiobodyparts_t {
    int32_t sznameindex;        // Offset to body part name
    int32_t nummodels;
    int32_t base;
    int32_t modelindex;         // Offset to models
};

// ============================================================================
// Model Structure (mstudiomodel_t)
// ============================================================================
struct mstudiomodel_t {
    char name[64];
    int32_t type;
    float boundingradius;
    int32_t nummeshes;
    int32_t meshindex;
    int32_t numvertices;
    int32_t vertexindex;        // Offset to vertex data (relative to VVD)
    int32_t tangentsindex;      // Offset to tangent data (relative to VVD)
    int32_t numattachments;
    int32_t attachmentindex;
    int32_t numeyeballs;
    int32_t eyeballindex;
    int32_t unused[8];
};

// ============================================================================
// Mesh Structure (mstudiomesh_t)
// ============================================================================
struct mstudiomesh_t {
    int32_t material;           // Material index
    int32_t modelindex;         // Model index

    int32_t numvertices;        // Number of unique vertices
    int32_t vertexoffset;       // Vertex offset within model

    int32_t numflexes;
    int32_t flexindex;

    int32_t materialtype;
    int32_t materialparam;

    int32_t meshid;

    glm::vec3 center;           // Mesh center

    int32_t unused[8];
};

// ============================================================================
// Hitbox Set (mstudiohitboxset_t)
// ============================================================================
struct mstudiohitboxset_t {
    int32_t sznameindex;
    int32_t numhitboxes;
    int32_t hitboxindex;
};

// ============================================================================
// Hitbox (mstudiobbox_t)
// ============================================================================
struct mstudiobbox_t {
    int32_t bone;
    int32_t group;
    glm::vec3 bbmin;
    glm::vec3 bbmax;
    int32_t szhitboxnameindex;
    int32_t unused[8];
};

// ============================================================================
// Sequence Description (mstudioseqdesc_t)
// ============================================================================
struct mstudioseqdesc_t {
    int32_t baseptr;            // Unused
    int32_t szlabelindex;       // Offset to sequence name
    int32_t szactivitynameindex; // Offset to activity name

    int32_t flags;
    int32_t activity;
    int32_t actweight;

    int32_t numevents;
    int32_t eventindex;

    glm::vec3 bbmin;
    glm::vec3 bbmax;

    int32_t numblends;

    int32_t animindexindex;     // Offset to anim indices
    int32_t movementindex;
    int32_t groupsize[2];
    int32_t paramindex[2];
    float paramstart[2];
    float paramend[2];

    int32_t seqparent;
    int32_t posekeyindex;

    int32_t numiklocks;
    int32_t iklockindex;

    int32_t keyvalueindex;
    int32_t keyvaluesize;

    int32_t cycleposeindex;

    int32_t activitymodifierindex;
    int32_t numactivitymodifiers;

    int32_t unused[8];
};

// ============================================================================
// Animation Description (mstudioanimdesc_t)
// ============================================================================
struct mstudioanimdesc_t {
    int32_t baseptr;
    int32_t sznameindex;
    float fps;
    int32_t flags;
    int32_t numframes;
    int32_t nummovements;
    int32_t movementindex;
    int32_t unused1[6];
    int32_t animblock;
    int32_t animindex;
    int32_t numikrules;
    int32_t ikruleindex;
    int32_t animblockikruleindex;
    int32_t numlocalhierarchy;
    int32_t localhierarchyindex;
    int32_t sectionindex;
    int32_t sectionframes;
    int32_t unused[8];
};

// ============================================================================
// VVD (Vertex Data) File Structures
// ============================================================================
struct vertexFileHeader_t {
    int32_t id;                 // MODEL_VERTEX_FILE_ID
    int32_t version;            // MODEL_VERTEX_FILE_VERSION
    int32_t checksum;           // Same as MDL checksum
    int32_t numLODs;
    int32_t numLODVertexes[8];  // Vertex count for each LOD
    int32_t numFixups;
    int32_t fixupTableOffset;
    int32_t vertexDataSize;
    int32_t tangentDataSize;
};

struct mstudioboneweight_t {
    float weight[3];
    int8_t bone[3];
    uint8_t numbones;
};

struct mstudiovertex_t {
    mstudioboneweight_t m_BoneWeights;
    glm::vec3 m_vecPosition;
    glm::vec3 m_vecNormal;
    glm::vec2 m_vecTexCoord;
};

// ============================================================================
// VTX (Optimized Vertex/Index Data) File Structures - Version 7
// ============================================================================
struct vtxFileHeader_t {
    int32_t version;            // 7 for Source 2013
    int32_t vertCacheSize;
    uint16_t maxBonesPerStrip;
    uint16_t maxBonesPerTri;
    int32_t maxBonesPerVert;
    int32_t checkSum;           // Same as MDL checksum
    int32_t numLODs;
    int32_t materialReplacementListOffset;
    int32_t numBodyParts;
    int32_t bodyPartOffset;
};

struct vtxBodyPart_t {
    int32_t numModels;
    int32_t modelOffset;
};

struct vtxModel_t {
    int32_t numLODs;
    int32_t lodOffset;
};

struct vtxModelLOD_t {
    int32_t numMeshes;
    int32_t meshOffset;
    float switchPoint;
};

struct vtxMesh_t {
    int32_t numStripGroups;
    int32_t stripGroupHeaderOffset;
    uint8_t flags;
};

struct vtxStripGroup_t {
    int32_t numVerts;
    int32_t vertOffset;
    int32_t numIndices;
    int32_t indexOffset;
    int32_t numStrips;
    int32_t stripOffset;
    uint8_t flags;
};

// Flags for vtxStripGroup_t
enum VtxStripGroupFlags : uint8_t {
    STRIPGROUP_TRIS = 0x01,
    STRIPGROUP_QUADS = 0x02,
};

struct vtxStrip_t {
    int32_t numIndices;
    int32_t indexOffset;
    int32_t numVerts;
    int32_t vertOffset;
    int16_t numBones;
    uint8_t flags;
    uint8_t numBoneStateChanges;
    int32_t boneStateChangeOffset;
};

// Flags for vtxStrip_t
enum VtxStripFlags : uint8_t {
    STRIP_IS_TRILIST = 0x01,
    STRIP_IS_TRISTRIP = 0x02,
};

struct vtxVertex_t {
    // Used to reconstruct the vertex in the VVD
    uint8_t boneWeightIndex[3];
    uint8_t numbones;
    uint16_t origMeshVertId;
    int8_t boneId[3];
};

#pragma pack(pop)

// ============================================================================
// Runtime Data Structures
// ============================================================================

struct Bone {
    std::string name;
    int32_t parent;
    glm::vec3 position;
    glm::quat rotation;
    glm::mat4 poseToBone;
    int32_t flags;
};

struct MDLVertex {
    glm::vec3 position;
    glm::vec3 normal;
    glm::vec2 texCoord;
    glm::vec3 tangent;
    std::array<float, 3> boneWeights;
    std::array<int8_t, 3> boneIds;
    uint8_t numBones;
};

struct MeshData {
    int32_t materialIndex;
    std::vector<MDLVertex> vertices;
    std::vector<uint32_t> indices;
    int32_t bodyPart;
    int32_t model;
    int32_t mesh;
};

struct AnimationSequence {
    std::string name;
    std::string activityName;
    int32_t activity;
    int32_t flags;
    float frameRate;
    int32_t numFrames;
    int32_t numBlends;
    int32_t animIndex;
};

struct SkinFamily {
    std::vector<int16_t> textures;  // Texture indices per skin reference
};

// ============================================================================
// Loaded MDL Model
// ============================================================================
class MDLModel {
public:
    MDLModel();
    ~MDLModel();

    // Load from file path (will use FileSystem to resolve)
    bool LoadFromFile(const std::string& path, const GameInfo& game);
    
    // Load from buffer (for VPK support)
    bool LoadFromBuffer(const std::vector<char>& buffer);

    // Accessors
    const std::vector<Bone>& GetBones() const { return m_bones; }
    const std::vector<MDLVertex>& GetVertices() const { return m_vertices; }
    const std::vector<uint32_t>& GetIndices() const { return m_indices; }
    const std::vector<std::string>& GetMaterialNames() const { return m_materialNames; }
    const std::vector<AnimationSequence>& GetSequences() const { return m_sequences; }
    const std::vector<MeshData>& GetMeshes() const { return m_meshes; }
    const std::vector<std::string>& GetTextureDirs() const { return m_textureDirs; }
    const std::vector<SkinFamily>& GetSkinFamilies() const { return m_skinFamilies; }
    
    int32_t GetNumBones() const { return static_cast<int32_t>(m_bones.size()); }
    int32_t GetNumVertices() const { return static_cast<int32_t>(m_vertices.size()); }
    int32_t GetNumIndices() const { return static_cast<int32_t>(m_indices.size()); }
    int32_t GetNumMaterials() const { return static_cast<int32_t>(m_materialNames.size()); }
    int32_t GetNumSequences() const { return static_cast<int32_t>(m_sequences.size()); }
    int32_t GetNumMeshes() const { return static_cast<int32_t>(m_meshes.size()); }
    int32_t GetNumSkinFamilies() const { return static_cast<int32_t>(m_skinFamilies.size()); }

    // Animation
    int32_t FindSequence(const std::string& name) const;
    std::string GetSequenceName(int32_t index) const;

    // Model info
    const std::string& GetName() const { return m_name; }
    float GetMass() const { return m_mass; }
    uint32_t GetFlags() const { return m_flags; }
    const glm::vec3& GetEyePosition() const { return m_eyePosition; }
    const glm::vec3& GetBoundingBoxMin() const { return m_bbMin; }
    const glm::vec3& GetBoundingBoxMax() const { return m_bbMax; }
    const glm::vec3& GetHullMin() const { return m_hullMin; }
    const glm::vec3& GetHullMax() const { return m_hullMax; }
    int32_t GetChecksum() const { return m_checksum; }
    int32_t GetVersion() const { return m_version; }
    
    // Surface property
    const std::string& GetSurfaceProp() const { return m_surfaceProp; }

private:
    bool ParseMDL(const uint8_t* data, size_t size);
    bool ParseVVD(const std::vector<char>& buffer);
    bool ParseVTX(const std::vector<char>& buffer);
    
    bool ParseHeader(const uint8_t* data, size_t size);
    bool ParseStudioHdr2(const uint8_t* data, size_t size);
    bool ParseBones(const uint8_t* data, size_t size);
    bool ParseTextures(const uint8_t* data, size_t size);
    bool ParseTextureDirs(const uint8_t* data, size_t size);
    bool ParseSkinFamilies(const uint8_t* data, size_t size);
    bool ParseBodyParts(const uint8_t* data, size_t size);
    bool ParseSequences(const uint8_t* data, size_t size);
    bool ParseHitboxSets(const uint8_t* data, size_t size);
    bool ParseSurfaceProp(const uint8_t* data, size_t size);
    bool ParseAttachments(const uint8_t* data, size_t size);
    
    bool BuildGeometry();
    
    std::string ResolveString(const uint8_t* base, int32_t offset) const;
    bool BoundsCheck(int32_t offset, size_t sizeNeeded, size_t fileSize) const;
    
    // Header data
    studiohdr_t m_header;
    std::unique_ptr<studiohdr2_t> m_header2;
    
    std::string m_name;
    float m_mass;
    uint32_t m_flags;
    int32_t m_checksum;
    int32_t m_version;
    glm::vec3 m_eyePosition;
    glm::vec3 m_bbMin, m_bbMax;
    glm::vec3 m_hullMin, m_hullMax;
    std::string m_surfaceProp;
    
    // Parsed data
    std::vector<Bone> m_bones;
    std::vector<MDLVertex> m_vertices;
    std::vector<uint32_t> m_indices;
    std::vector<std::string> m_materialNames;
    std::vector<std::string> m_textureDirs;
    std::vector<AnimationSequence> m_sequences;
    std::vector<SkinFamily> m_skinFamilies;
    std::vector<MeshData> m_meshes;
    
    // Raw file data for parsing
    std::vector<char> m_mdlData;
    std::vector<char> m_vvdData;
    std::vector<char> m_vtxData;
    const uint8_t* m_baseData = nullptr;
};

// ============================================================================
// MDL Model cache for efficient loading
// ============================================================================
class MDLCache {
public:
    static MDLCache& Get();
    
    std::shared_ptr<MDLModel> LoadModel(const std::string& path, const GameInfo& game);
    void UnloadModel(const std::string& path);
    void Clear();
    
private:
    MDLCache() = default;
    std::unordered_map<std::string, std::shared_ptr<MDLModel>> m_models;
};

} // namespace veex
